### ISSUE TITLE
Update template to use latest dependencies

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nuxt-community/typescript-template#24]
Right now the template uses quite outdated version of Nuxt as well as other project dependencies. Please, update all project dependencies to use latest available packages. Upgrading manually causes issues right now

**Comment by jasonc08** [comment]
+1

**Comment by kalaomer** [comment]
Yeah, I tried manually but nuxt did not get store module, because it looks js file which's and with ".js".

**Comment by qm3ster** [comment]
It's happening in #27

**Comment by qm3ster** [comment]
fixed in #27

**Comment by AndrewBogdanovTSS** [comment]
not entirely fixed due to remaining issues with `npm` installation process present after #27 was merged

**Comment by qm3ster** [comment]
@AndrewBogdanovTSS the adventure continues in #29
